In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("astronautas.csv")
data

,nombre,genero,anio_nacimiento,nacionalidad,status,ocupacion,anio_mision,edad_mision,mision_hs,eva_mision_hs
0,Aleksandr Kaleri,masculino,1956,U.S.S.R/Rusia,civil,ingeniero aeroespacial,2010,54,3824.00,0.00
1,Yuri Malenchenko,masculino,1961,U.S.S.R/Rusia,militar,comandante,2012,51,3047.00,5.85
2,Yuri Malenchenko,masculino,1961,U.S.S.R/Rusia,militar,comandante,2015,54,1477.00,4.72
3,Catherine G. Coleman,femenino,1960,EE.UU.,militar,ingeniero aeroespacial,2011,51,3823.00,0.00
4,Chris Hadfield,masculino,1959,Canada,militar,piloto,2012,53,3710.32,0.00
...,...,...,...,...,...,...,...,...,...,...
152,Anne Charlotte McClain,femenino,1979,EE.UU.,militar,ingeniero aeroespacial,2018,39,4887.00,13.13
153,Christina Koch,femenino,1979,EE.UU.,civil,ingeniero aeroespacial,2019,40,7372.30,27.80
154,Andrew Morgan,masculino,1976,EE.UU.,militar,ingeniero aeroespacial,2019,43,4303.08,39.52
155,Jessica Meir,femenino,1977,EE.UU.,civil,ingeniero aeroespacial,2019,42,2697.60,7.28
156,Hazzaa Al Mansoori,masculino,1983,Emiratos Arabes Unidos,militar,participante de vuelo espacial,2019,36,189.00,0.00